---
kind: ProjectRequest
apiVersion: project.openshift.io/v1
metadata:
  name: parks-app

---
kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: restify
  namespace: parks-app
  labels:
    app: restify
spec: {}
status:
  dockerImageRepository: ''

---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: restify
  namespace: parks-app
  labels:
    app: restify
spec:
  triggers:
  - type: GitHub
    github:
      secret: 4Xwu0tyAab90aaoasd88qweAasdaqvjknfrl3qwpo
  - type: Generic
    generic:
      secret: 4Xwu0tyAab90aaoasd88qweAasdaqvjknfrl3qwpo
  - type: ConfigChange
  - type: ImageChange
    imageChange: {}
  source:
    type: Git
    git:
      uri: https://github.com/konveyor/mig-demo-apps
      ref: master
    contextDir: apps/parks-app/src
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: DockerImage
        name: 'registry.redhat.io/ubi9/nodejs-20:latest'
  output:
    to:
      kind: ImageStreamTag
      name: "restify:latest"
  resources: {}
status:
  lastVersion: 0

---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: restify
  namespace: parks-app
  labels:
    app: restify
spec:
  strategy:
    resources: {}
  triggers:
  - type: ConfigChange
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - restify
      from:
        kind: ImageStreamTag
        name: "restify:latest"
  replicas: 1
  selector:
    app: restify
    deploymentconfig: restify
  template:
    metadata:
      creationTimestamp:
      labels:
        app: restify
        deploymentconfig: restify
    spec:
      volumes:
      - name: "restify-volume-1"
        emptyDir: {}
      initContainers:
      - name: wait-for-mongodb
        image: 'docker.io/library/mongo:7.0'
        command:
        - /bin/bash
        - -c
        - |
          set +e  # Don't exit on error
          
          echo "==========================================="
          echo "Waiting for MongoDB service to be ready..."
          echo "==========================================="
          
          MAX_ATTEMPTS=60
          SLEEP_TIME=5
          SUCCESS=0
          
          for i in $(seq 1 $MAX_ATTEMPTS); do
            echo ""
            echo "Attempt $i/$MAX_ATTEMPTS: Testing MongoDB connectivity..."
            
            # Method 1: Test with mongosh (most reliable - actual MongoDB protocol test)
            if command -v mongosh >/dev/null 2>&1; then
              echo "  → Testing with mongosh..."
              if timeout 10 mongosh --host mongodb --port 27017 --eval "db.adminCommand('ping')" >/dev/null 2>&1; then
                echo "  ✅ MongoDB is ready and responding to commands!"
                SUCCESS=1
                break
              fi
            fi
            
            # Method 2: Test with legacy mongo client
            if command -v mongo >/dev/null 2>&1; then
              echo "  → Testing with mongo client..."
              if timeout 10 mongo --host mongodb --port 27017 --eval "db.adminCommand('ping')" >/dev/null 2>&1; then
                echo "  ✅ MongoDB is ready and responding to commands!"
                SUCCESS=1
                break
              fi
            fi
            
            # Method 3: Simple port connectivity test as fallback
            echo "  → Testing port connectivity..."
            if timeout 5 bash -c 'cat < /dev/null > /dev/tcp/mongodb/27017' 2>/dev/null; then
              echo "  ✅ MongoDB port 27017 is open and accepting connections!"
              SUCCESS=1
              break
            fi
            
            # Method 4: Try nc if available
            if command -v nc >/dev/null 2>&1; then
              echo "  → Testing with nc..."
              if timeout 5 nc -z mongodb 27017 2>/dev/null; then
                echo "  ✅ MongoDB port is reachable via nc!"
                SUCCESS=1
                break
              fi
            fi
            
            echo "  ⏳ MongoDB not ready yet, waiting ${SLEEP_TIME} seconds..."
            sleep $SLEEP_TIME
          done
          
          echo ""
          echo "==========================================="
          if [ $SUCCESS -eq 1 ]; then
            echo "✅ SUCCESS: MongoDB is ready!"
            echo "==========================================="
            exit 0
          else
            echo "⚠️  WARNING: Could not verify MongoDB after $MAX_ATTEMPTS attempts"
            echo "Proceeding anyway - application will retry connections..."
            echo "==========================================="
            exit 0  # Don't fail the pod, let the app handle retries
          fi
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      containers:
      - name: restify
        image: library/restify:latest
        ports:
        - containerPort: 8080
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 15
        env:
        - name: DATABASE_SERVICE_NAME
          value: mongodb
        - name: MONGODB_DATABASE
          value: restify-database
        - name: MONGODB_DB_URL
          value: mongodb://mongodb:27017
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        volumeMounts:
        - name: "restify-volume-1"
          mountPath: "/run"
status: {}

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: restify
  namespace: parks-app
  labels:
    app: restify
spec:
  to:
    kind: Service
    name: restify
  port:
    targetPort: '8080'
status: {}

---
kind: Service
apiVersion: v1
metadata:
  name: restify
  namespace: parks-app
  labels:
    app: restify
spec:
  ports:
  - name: 8080-tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    app: restify
status:
  loadBalancer: {}

---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: mongodb
  namespace: parks-app
spec:
  strategy:
    type: Recreate
  triggers:
  - type: ConfigChange
  replicas: 1
  selector:
    name: mongodb
  template:
    metadata:
      labels:
        name: mongodb
    spec:
      containers:
      - name: mongodb-container
        image: 'docker.io/library/mongo:7.0'
        ports:
        - containerPort: 27017
          protocol: TCP
        env:
        - name: MONGODB_USER
          value: mongo-user-1
        - name: MONGODB_PASSWORD
          value: mongo-user-password
        - name: MONGODB_DATABASE
          value: restify-database
        - name: MONGODB_ADMIN_PASSWORD
          value: moogo-admin-pass
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "mongosh --eval 'db.runCommand(\"ping\")' --quiet"
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - "mongosh --eval 'db.runCommand(\"ping\")' --quiet"
          initialDelaySeconds: 60
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
        imagePullPolicy: Always
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-data-claim
      restartPolicy: Always

---
kind: Service
apiVersion: v1
metadata:
  name: mongodb
  namespace: parks-app
spec:
  ports:
  - name: mongo
    protocol: TCP
    port: 27017
    targetPort: 27017
  selector:
    name: mongodb
  type: ClusterIP
  sessionAffinity: None
status:
  loadBalancer: {}

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: "mongodb-data-claim"
  namespace: parks-app
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
